### ISSUE TITLE
BungeeCord mode

### ISSUE THREAD

**Issue by Timpixel2020** [filoghost/ChestCommands#102]
### Description

I suggest adding a mode - Viewing online on another server! For example, "Online {online: SkyWars}", which will be displayed online on another BungeeCord server(Example SkyWars)! Add this mode, please!

**Comment by ZipName80** [comment]
you can use it with Placeholder API

**Comment by Timpixel2020** [comment]
> you can use it with Placeholder API

I have PAPI! How i can load this: /papi ecloud download {???}

**Comment by filoghost** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bungeecord

A basic BungeeCord integration may be added directly in Chest Commands in the future. I will keep this issue open as reminder.

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
