### ISSUE TITLE
Animated Menu

### ISSUE THREAD

**Issue by Timpixel2020** [filoghost/ChestCommands#103]
### Description

I suggest making an Animated menu, for example, at the beginning of the file there will be a line - "animated-menu: true", which will make the menu animated, for example:
--------------------------------------------------
LORE:
 - '\/ Look to me) I'm animation \/'
 '1':
 - 'Animation 1'
 - 'Animation 2'
 - 'Animation 3'
 --------------------------------------------------
Add this please! It will be useful for everyone, than to install some other plugins and try to transfer the existing menu to the same plugins 😉
Try to do it for everyone ;)

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
