### ISSUE TITLE
Slow Placeholder animations

### ISSUE THREAD

**Issue by Timpixel2020** [filoghost/ChestCommands#104]
### Platform

- Server version (output of `/version`): 
- Chest Commands version (check with `/cc`): 

### Additional context

If i do "%animations_<flash>&a▶ Нажмите, что бы играть...</flash>%"
and enter /cc reload, animation in menu must slow...I write speed=1, but this doesn't work. But in others plugins it is soo fast, and work "speed" option! What i can do?
--------------------------------------------
Version of server: spigot-1.15.jar
ChestCommands version: 4.0.3
Help me pls!!!

**Comment by filoghost** [comment]
It depends on the `auto-refresh` option of the menu, which by default is 5 seconds. Be warned, a single slow placeholder can cause the server to slow down, but you can set `auto-refresh` to 0.05 seconds (which is every tick).
