### ISSUE TITLE
Delay mode

### ISSUE THREAD

**Issue by Timpixel2020** [filoghost/ChestCommands#112]
### Description

Add please: "Delay mode", this mode has been do delay between commands!
Example:
ACTIONS:
 - 'op: spawn'
 -  'delay=2' (Time in seconds)
 - 'tell: &2Ypu has been teleported to spawn!'

Add this please!
View this! Author!

**Comment by Chiquis2005** [comment]
does not work for me

**Comment by filoghost** [comment]
Sorry, won't add this. This should be implemented through external plugins, similarly to one-time commands. You can also use Skript for more complex commands.
