### ISSUE TITLE
Required Items with custom names/NBT/lore

### ISSUE THREAD

**Issue by Hax0nWax0ff** [filoghost/ChestCommands#114]
### What are you trying to do?

I would like to create a custom currency with a certain player head with a set NBT, and then use chestcommands as a shop for it and have the required items only take a player head with a certain name/NBT/lore rather than just take any player head in the players inventory.

### What have you tried so far?

I have tried adding in the "NBT-DATA:" line and value within the required items area everwhere i thought it would work; above, below, within, next -'' line, etc, but no luck.

### Platform

- Server version (output of `/version`): git-Paper-469 (MC: 1.16.5) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Chest Commands version (check with `/cc`): 4.0.3

**Comment by filoghost** [comment]
This is not possible currently, the REQUIRED-ITEMS options only checks material, durability and amount.

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
