### ISSUE TITLE
Sub menu 3

### ISSUE THREAD

**Issue by abc110210** [filoghost/ChestCommands#115]
### Platform

- Server version (output of `/version`): 
- Chest Commands version (check with `/cc`): 

### Additional context

I use CC to open the second menu
And then when you go to the third menu from the submenu it goes back to the main CC menu
For CMI and anything that has a submenu it goes back to the main menu of CC

**Comment by filoghost** [comment]
Sorry, I don't know if I understood, but a "back button" doesn't exist as a feature, so you must manually add an icon that opens the parent menu. So if A opens B, and B opens C, you must add an icon with "open: A" inside B, and an icon with "open: B" inside C.

This is not s bug, to clarify.
