### ISSUE TITLE
Bug report : Stained_glass_pane with color variation doesn't work

### ISSUE THREAD

**Issue by Xxitra** [filoghost/ChestCommands#118]
### Description

Hello, I have a problem with the plugin, I am trying to put the object "stained_glass_pane" as a material but in the color blue (160: 11).
I checked the documentation and saw that it had to be put like this: stained_glass_pane: 11
However this does not work, it just lets me put stained_glass_pane, if I put stained_glass_pane: 11 it gives me the error "The icon" Slot 5 "in the menu * path * has an invalid attribute" MATERIAL ": unknow material" stained_glass_pane: 11 "
And it not only happens to me with this object, if not with all those that have color variations.

### How to reproduce

1. Open the custom menu .yml
2. Create a new icon
3. In the material section put stained_glass_panel: 11
4. Fill in the other sections correctly
5. Reload the plugin with /cc reload or close and open the server
6. You get the error

### Platform

- Server version (output of `/version`): 1.12.2
- Chest Commands version (check with `/cc`):  4.0.3

### Additional context

![image](https://user-images.githubusercontent.com/56980480/108904934-1aaa4f00-75ed-11eb-9516-7d5ba5864834.png)
![image](https://user-images.githubusercontent.com/56980480/108904973-2269f380-75ed-11eb-8cbc-e4f78ea40911.png)
![image](https://user-images.githubusercontent.com/56980480/108905019-301f7900-75ed-11eb-8ae3-16fdcb67e5ae.png)
![image](https://user-images.githubusercontent.com/56980480/108905239-7674d800-75ed-11eb-96cb-b017882ff902.png)

**Comment by filoghost** [comment]
You now need to use the separate DURABILITY option. The up to date documentation is here: https://filoghost.me/docs/chest-commands
