### ISSUE TITLE
[Request] ItemJoin item support

### ISSUE THREAD

**Issue by TheRobLP** [filoghost/ChestCommands#123]
### Description

Good day. I am Administrator and Support of CraftationGaming, the server of the plugin ItemJoin. It was recently brought to our attention that ChestCommands has some problems with importing items from this plugin. Since ItemJoin is fairly popular, it would most likely benefit many users. I would like to ask if you could implement support for adding ItemJoin items in a Chest GUI. The plugin has it's own API to integrate with other plugins: https://github.com/RockinChaos/ItemJoin/blob/master/src/me/RockinChaos/itemjoin/api/ItemJoinAPI.java

Would this be possible? Thank you very much in advance for any answer.

Sincerely
TheRobLP

**Comment by RockinChaos** [comment]
To clarify a bit--we have users requesting the ability to have an ItemJoin item defined inside a Chest GUI with retained functionality (functionality is already handled by ItemJoin). So if there was an elegant way to add the ability to define the `item-node` of an item in ChestCommands where it could then be fed into the above provided API which will fetch that item for the specific user and return an ItemStack that could be placed into the Chest GUI.

Thanks for reading.

**Comment by filoghost** [comment]
This is a rather specific need, I think you should use the API of Chest Commands for this level of customization. Why do you need to also place an item from ItemJoin inside the menu?

**Comment by RockinChaos** [comment]
So from what I understand regarding the API is that it allows you to create new menus not add items to an existing opened viewer that is defined via ChestCommands? The users that request this feature are asking for actual implementation into their menu files.

As for `Why do you need to also place an item from ItemJoin inside the menu?` I honestly have no clue, I can try to send them over here to answer that question--We are just simply relaying a feature request.

From what I can tell is that they say, certain ItemJoin materials have more functionality than what ChestCommands provides mainly regarding player heads and wool I guess (whether that is true I am not sure they may just be missing a feature that already exists, I use ChestCommands myself but not in that way).

Anyways I pinged them and asked them to respond here.

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
