### ISSUE TITLE
Failed to start plugin

### ISSUE THREAD

**Issue by BautistaIza** [filoghost/ChestCommands#124]
### Description
When trying to start the server it tells me that there was a Fatal Error

### How to reproduce
When starting the server

### Platform
- Server version git-Paper-567 (MC: 1.16.5)
- Chest Commands version (I can't use the command`): 

### Fatal error
https://pastebin.com/rmNhuEWw

**Comment by filoghost** [comment]
I'm not able to reproduce this error. It might be a conflicting plugin registering a weird enchantment, try on a clean server without other plugins.

How to find a potentially conflicting plugin:
* Copy your whole server
* Remove all the plugins except Chest Commands
* If it doesn't work, stop here and tell me
* Add plugins back until Chest Commands doesn't work anymore
* The conflicting plugin is the one that breaks  Chest Commands when enabled

**Comment by xzferchu** [comment]
Did you resolve this? I have the same fatal error (log) in my console and I dont know what it can be.

**Comment by filoghost** [comment]
Please try on a clean server without other plugins.
