### ISSUE TITLE
Plan placeholders not showing

### ISSUE THREAD

**Issue by Miluek** [filoghost/ChestCommands#127]
### What are you trying to do?

I want placeholders to work for me

### What have you tried so far?

Nothing, I don't know

### Platform

- Server version (output of `/version`):  1.16.5 - R0.1 - snapshot
- Chest Commands version (check with `/cc`): 4.0.3

### Additional context

Other placeholders working well, but placeholders from plan not...
Can you help me please?

**Comment by filoghost** [comment]
I don't know what plan is, but if other placeholders work that's not Chest Commands' fault. Try asking the author of that plugin.
