### ISSUE TITLE
Can't open GUIs inside of a GUI

### ISSUE THREAD

**Issue by TheSpotSMP** [filoghost/ChestCommands#128]
### Description
 When trying to perform a command that would open another gui inside of a GUI it instantly closes.

### How to reproduce

Add a GUI command into a chestcommands gui and click it.

### Platform

- Server version (output of `/version`):  1.16.5 Purpur
- Chest Commands version (check with `/cc`):  4.0.4-SNAPSHOT-B75

**Comment by FZDNSZYT** [comment]
Mine is the same. I can’t open the GUI of other plugins in the menu. I hope the author will solve this problem as soon as possible.

**Comment by headblockhead** [comment]
Try using this
(like this:
```
ACTIONS:
    - 'open: shop.yml' 
```
)

**Comment by headblockhead** [comment]
If you want to open another chest commands GUI you can use:
```
  ACTIONS:
    - 'open: shop.yml'

```
But in terms of other plugin's' GUI, we'll just have to wait for the author to fix this.

**Comment by FZDNSZYT** [comment]
Yes, I did use ChestCommands to open the GUI of other plugins. I am in trouble, and the system prompts me to open it successfully. And there are sound effects, but the GUI interface will crash. Cannot be displayed.

**Comment by headblockhead** [comment]
I haven't tested, but you might me able to use a Skript script that closes
the chest commands GUI, waits 3 ticks and then opens the other plugin's GUI.

In theory it SHOULD work but I'm not sure if it would be possible to close
the chest commands GUI with Skript.


Also what do you mean by this?

```

I am in trouble, and the system prompts me to open it successfully.

```

Is there some context I'm missing here?

If I make no sense (or get something wrong) in this reply, i'll make an
edit when I have the chance.

Hope this helps!

**Comment by filoghost** [comment]
Have you tried using `KEEP-OPEN: true`? It will prevent Chest Commands from closing the GUI

**Comment by FZDNSZYT** [comment]
Thank you, I will try it later. thank you very much.

**Comment by FZDNSZYT** [comment]
Where can I download the script of the friend above, thank you

**Comment by FZDNSZYT** [comment]
ChestCommands is the best MENU plugin I have ever used. Dear author. Up to now, there is no MENU configuration interface that can match you. in my heart.

**Comment by headblockhead** [comment]
Here is the script. I have tested it now.
```
command /openplugingui:
    description: Closes the inventory and opens another one
    trigger:
        close player's inventory
        wait 3 ticks
        make player execute command "say hello"
```
Here is the ChestCommand icon
```
open-plugin-menu:
  MATERIAL: barrier
  POSITION-X: 9
  POSITION-Y: 3
  NAME: '&cOpen Other Menu'
  LORE:
    - 'Opens another plugins gui'
  ACTIONS:
    - 'openplugingui'
```

**Comment by FZDNSZYT** [comment]
May I ask if I should add command /openplugingui:
     description: Closes the inventory and opens another one
     trigger:
         close player's inventory
         wait 3 ticks
         Where is the make player execute command "companions" script? When I put it in the menu file under the MENU directory, the following error occurred.

**Comment by FZDNSZYT** [comment]
FZDNSZYT issued server command: /chestcommands RELOAD
[21:12:27 INFO]: [ChestCommands] Encountered 5 error(s) on load:
 
1) The icon "command /openplugingui" in the menu "menu/example.yml" has an invalid attribute "description": unknown attribute.
 
2) The icon "command /openplugingui" in the menu "menu/example.yml" has an invalid attribute "trigger": unknown attribute.
 
3) The icon "command /openplugingui" in the menu "menu/example.yml" is missing the attribute "POSITION-X".
 
4) The icon "command /openplugingui" in the menu "menu/example.yml" is missing the attribute "POSITION-Y".
 
5) The icon "command /openplugingui" in the menu "menu/example.yml" is missing the attribute "MATERIAL".

**Comment by FZDNSZYT** [comment]
companions is a command to open the pet plug-in GUI. I hope I didn't understand what you mean wrong, author boss.

**Comment by FZDNSZYT** [comment]
I'm sorry, I do not speak English. I use Google Translate to communicate with you. There may be obstacles, I'm really sorry.

**Comment by headblockhead** [comment]
Sorry, I wasn't very clear with the previous comment, there is a separate plugin called "Skript" [at this website](https://github.com/SkriptLang/Skript/releases) and i wrote a file for that. After installing the plugin, place the file below in your minecraft server at "/plugins/Skript/scripts/openplugingui.sk" then start the server.
then it should work.
```
command /openplugingui:
    description: Closes the inventory and opens another one
    trigger:
        close player's inventory
        wait 3 ticks
        make player execute command "say hello"
```
