### ISSUE TITLE
Head doesn't changes

### ISSUE THREAD

**Issue by LordNetlocDev** [filoghost/ChestCommands#129]
### Description

If change Value in NBT-DATA for Head in menu, head doesn't changes

### Platform

- Server version (output of `/version`):  Paper 1.12.2 
- Chest Commands version (check with `/cc`): lastes version 4.0.3

### Additional context

Config: https://pastebin.com/yN0nH1i3

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
