### ISSUE TITLE
I DO NOT find a video / site that describes how to redirect to another menu from the main

### ISSUE THREAD

**Issue by HardRoma** [filoghost/ChestCommands#131]
I want to redirect to other menus from the main, but there are no new sites / videos with the changed ones.
For example:
Donate:
COMMAND: 'open donate.yml'
MATERIAL: dirt
POSITION-X: 2
POSITION-Y: 1
NAME: '&aDonate'
LORE:

**Comment by rp2709** [comment]
Hey! Don't know if you found a way around this already but you need to set "KEEP-OPEN : true" for the menu to open. BTW this is totaly on the wiki page.
