### ISSUE TITLE
cooldown / delay for a menu

### ISSUE THREAD

**Issue by IZABELLUDVICHAK** [filoghost/ChestCommands#134]
### Description

a cooldown option that could be used in a single menu would be very useful, it would be good for some types of commands that should not be flooded, example: give, time set, start event, etc.
the command code could be something like
COOLDOWN: '120 (seconds)'

this option could be complemented with something like
COOLDOWN_MSG: 'wait (% time%) to use this option again

I await response, grateful for your attention

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
