### ISSUE TITLE
I need help with my files!

### ISSUE THREAD

**Issue by GremlinRepoioxd** [filoghost/ChestCommands#140]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

Hello, good morning, I have a problem with a configuration on my server and that is that I was changing the text and after making all the change, I started my server and I jump 2 errors only, the error is as follows:

#------------------- Chest Commands Errors/Warnings -------------------#
1) Invalid YAML configuration for the menu "doubles.yml". Please look at the error above, or use an online YAML parser (google is your friend).
2) Invalid YAML configuration for the menu "menu.yml". Please look at the error above, or use an online YAML parser (google is your friend).
#----------------------------------------------------------------------#
[10:28:47 INFO]: [ChestCommands] Plugin reloaded with 2 error(s).

### Chest Commands version

ChestCommands version 3.5.6

**Comment by nyny07** [comment]
Bonjour auriez vous les deux fichier config qui pose un souci pour voir d'où pourrez venir celui-ci

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
