### ISSUE TITLE
Sending player to another Bungee server bypasses server restrictions.

### ISSUE THREAD

**Issue by DarkKingKaan** [filoghost/ChestCommands#141]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

I have a menu item that sends a player to the Factions server. The server is currently only available for beta testers, so I have set the server as "restricted" in bungeecord config, which makes players unable connect or even view the server without a permission (in this case bungeecord.server.factions). The problem is, when setting a click action on a menu item to send someone to a bungee server, it bypasses this restriction (I'm guessing because the plugin uses the same system as the /send command). I think the plugin shouldn't bypass these bungeecord restrictions or we should be able to set a permission to use/click on a specific item in the menu.

### How to reproduce

1. Have a Bungeecord network setup
2. Set one server as "restricted"
3. Try to access the server without permissions, using /server command, shouldn't work.
4. Setup a menu item and set a click action to send a player to a bungee server
5. Try to access the same restricted server using the menu without permissions, it works.

### Server version

Paper 1.15.2

### Chest Commands version

Chest Commands v4.0.3

**Comment by filoghost** [comment]
Unfortunately the plugin cannot check the permissions on BungeeCord, only on the Bukkit/Spigot server.
