### ISSUE TITLE
Ability to have separate actions based on how an item is interacted with

### ISSUE THREAD

**Issue by GemPvP** [filoghost/ChestCommands#142]
### Description

Title says it all. It would be nice to be able to run different actions/commands based on how a player interacts with an item in a GUI. For example, if a player right-clicked an item it would sell 64 sugar cane, if a player left-clicked that same item it would buy 64 sugar cane.

I'm mainly looking to see a left and right-clicking variation implemented, but a middle-click/hotkey functionality would be nice also (hover over an item and press "1" or "2" or "3", etc...

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
