### ISSUE TITLE
how to open another plugin's menu

### ISSUE THREAD

**Issue by TalentNana** [filoghost/ChestCommands#143]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

How can I use other plugin's menu, the plugin have its own menu, and I try ro use Chest Commands to open the menu, but it does have any reaction, only CC's menu disappeared. The console mentioned that I used command to open other plugin's menu, but nothing happened

### Chest Commands version

version4.04

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
