### ISSUE TITLE
How to right click on a custom item to open the store?

### ISSUE THREAD

**Issue by TIM31205** [filoghost/ChestCommands#146]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

I tried to use various formats. But it seems to only be able to enter the item ID.

### Chest Commands version

Chest Commands v4.0.3

### Additional information

(sorry my english is not good)
Just like the title, I want to allow players to use custom items to open the store, for example: restrict only custom item names to open the store

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
