### ISSUE TITLE
Remove the "Opening the menu " confirmation

### ISSUE THREAD

**Issue by qxZap** [filoghost/ChestCommands#149]
### Description

Looks like whatever you do, you are going to have that on your chat since the order is this:
- check permissions
- send confirmation message 
- open menu
And the confirmation part does not check any permission.
@ /plugin/src/main/java/me/filoghost/chestcommands/command/CommandHandler.java lines 156-160

**Comment by FabioII** [comment]
same here. Every time I get the Message "Opening the menu language.yml"

That is very annoying...

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.

**Comment by AIGLE25** [comment]
i realy need a fix to that problem too

**Comment by filoghost** [comment]
Use the "OPEN" action. Not /cc command, that's supposed to be admin-only.

**Comment by AIGLE25** [comment]
> Use the "OPEN" action. Not /cc command, that's supposed to be admin-only.

i am trying to open menu with npc , but idk how to perform action without npc commands

**Comment by AIGLE25** [comment]
i want to use the command with npx but seem not working , when i do "/npc cmdadd open MiniSolo.yml" it open the Solo menu
