### ISSUE TITLE
"MATERIAL: PLAYER_HEAD"The texture display problem of the player's head

### ISSUE THREAD

**Issue by FZDNSZYT** [filoghost/ChestCommands#152]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

In the following series of configuration units, "MATERIAL: PLAYER_HEAD" can only display Steve's head without skin. But I want him to show the player's head with skin texture. May I ask you ruh?

### Chest Commands version

4.0.3

### Additional information

two5:
   MATERIAL: PLAYER_HEAD
   POSITION-X: 5
   POSITION-Y: 3
   NAME:'&4&l'
   LORE:
     -'&4Right click to open the Admin menu'
   ACTIONS:
     -'open:Admin.yml'
   PERMISSION-MESSAGE:'&c&lYou do not have permission to use the management menu.'

**Comment by wayff1** [comment]
Такая же проблема(

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
