### ISSUE TITLE
The icon "spawn-command" in the menu "menu/example.yml" has an invalid attribute "MATERIAL": unknown material "SKULL:3"

### ISSUE THREAD

**Issue by LMS5413** [filoghost/ChestCommands#155]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

I was setting up chest commands in 1.12.2 and wanted it by skull. But when I put an item with the ID of this error even though it is valid even with the ID of the head of the error

### How to reproduce

In material put 397:3
that the error will appear

### Server version

This server is running Mohist version 1.12.2-261 CMC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855)

### Chest Commands version

4.0.3

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
