### ISSUE TITLE
[Suggestion] Add a delay option

### ISSUE THREAD

**Issue by sylphrena0** [filoghost/ChestCommands#159]
### Description

I have some commands in one of my menus that will not work - commands that open other menus from other plugins. I suspect this is because the commands are being issues while the menu is still open, preventing it from opening.

Could you add a delay actions option to allow us to bypass this issue?

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
