### ISSUE TITLE
 Implementation of 2 currencies

### ISSUE THREAD

**Issue by ivansherbakov9** [filoghost/ChestCommands#160]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

Help me please! How to make it so that when buying, it is not the Vault currency that is taken away, but the 2 currency created by another plugin?
tipped_arrow2:
  MATERIAL: 440
  AMOUNT: 32
  POSITION-X: 6
  POSITION-Y: 2
  NAME: ''
  LORE:
    - '&c20 ₵'
    - '&c%playerpoints_points% ₵'
  ACTIONS:
    - 'console: give {player} potion 1 5 { CustomPotionEffects: [ { Id:25,Amplifier:5,Duration:150 } ] }'
    - 'console: give {player} 261 1'
  KEEP-OPEN: true 

It is necessary that when pressed, an item is given and 20 coins are taken away.

### Chest Commands version

chestcommands-4_0_3.jar

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
