### ISSUE TITLE
opening command

### ISSUE THREAD

**Issue by rejvic** [filoghost/ChestCommands#163]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

Okay, so before updating to the latest version I was able to use commands with certain follow-ups. Let's take '/kit' for instance. The command defined in the file is 'kit' but I was able to use '/kit example' to receive a certain kit. And after I've updated to the latest version, every follow-up syntax just opens a menu and doesn't execute the command. Is there a certain suffix I should add to the command defined in the menu file or is there an alternative to this?

### Chest Commands version

latest

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
