### ISSUE TITLE
Can i trade items

### ISSUE THREAD

**Issue by AgatraA** [filoghost/ChestCommands#165]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

Can i use one item example dirt to trade on the gui and get a diamond. And if i can, can i do it with armor? Example : netherite block for netherite armor. And of it works, can i change the name of the item? So when i trade/buy the item i get have a custom name and lore?
Is this all possible?

### Chest Commands version

Newest on aternos

### Additional information

.

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
