### ISSUE TITLE
Can i use defaut item in my menu ?

### ISSUE THREAD

**Issue by Axpox45VN** [filoghost/ChestCommands#166]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

![image](https://user-images.githubusercontent.com/96615225/150620762-6eb54d94-2742-431e-b274-6788e36ec646.png)

### Chest Commands version

Chestcommand 4.0.3

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
