### ISSUE TITLE
PRIORITY

### ISSUE THREAD

**Issue by c00rnell** [filoghost/ChestCommands#167]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

I need help from someone who know to use ChestCommands:
Is it any way to make a icon to be priority?

If you have example permission "test.test" you can see a green wool
If you dont have the permssions you will see bedrock

### Chest Commands version

ChestCommands Version 4.0.3

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
