### ISSUE TITLE
MATERIAL: '160:16' or stained_glass_pane:16 or thing like so aren't working

### ISSUE THREAD

**Issue by Sohgan** [filoghost/ChestCommands#170]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

Hello, i think there are many questions of this type, BUT after reading some guys who answered (as the same question as me) i found no issue. So i don't know what to do. I need help please !

### Chest Commands version

4.0.3

### Additional information

**In game when i reload the plugin (/cc reload) :**

[ChestCommands] Plugin reloaded with 1 error(s).
[ChestCommands] Please check the console.

**In the console :**

The icon "bsg1" in the menu "menu\mainmenu.yml" has an invalid attribute "MATERIAL": unkown material "160:16".

**Comment by filoghost** [comment]
Please read here if you still have the issue: https://filoghost.me/docs/chest-commands/upgrade-1.13

Using the data value like that doesn't work in 1.13 and above, you'll have to use NBT-DATA.
