### ISSUE TITLE
Red command / unknown command

### ISSUE THREAD

**Issue by lynrayy** [filoghost/ChestCommands#171]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [x] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Menu is existing but minecraft says that there is no such command 
![image](https://user-images.githubusercontent.com/59417884/160971660-e155b5bc-a52c-45df-92c6-24908c0724aa.png)

There is no way to fix it in config or menu.yml

### How to reproduce

Created menu
Reloaded plugin
Command is red

### Server version

This server is running Paper version git-Paper-270 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fa68bb1) You are 2 version(s) behind Download the new version at: https://papermc.io/downloads

### Chest Commands version

4.0.4

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/160971834-522da809-9cd9-4c85-9712-9e3d6766320e.png)
There is a menu

**Comment by priyam1234-spec** [comment]
do u have multiple guis?

**Comment by lynrayy** [comment]
No i have only this (menu.yml where i set comman "- menu"

**Comment by priyam1234-spec** [comment]
It will stay red but the gui will work

**Comment by lynrayy** [comment]
I need it white. Any solution?

**Comment by filoghost** [comment]
The commands need to be dynamically registered, so the server doesn't know they exists.
