### ISSUE TITLE
How to disable the auto update ?my server running in 1.7.10.

### ISSUE THREAD

**Issue by ly19811105** [filoghost/ChestCommands#175]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

17:31:17 INFO]: [Thermos] Refusing to lock affinity, disabled in cauldron.yml
[17:31:19 INFO]: [ChestCommands] Found a new version: v4.0.3 (yours: v3.3.1)
[17:31:19 INFO]: [ChestCommands] Download it on Bukkit Dev:
[17:31:19 INFO]: [ChestCommands] dev.bukkit.org/bukkit-plugins/chest-commands

the server always stack on update the new version. and v4.0.3 not support 1.7.10 .So how to disable the update?

### Chest Commands version

version: v3.3.1

**Comment by filoghost** [comment]
There should be an option in config.yml about update notifications.
