### ISSUE TITLE
I can't connect to an other server.

### ISSUE THREAD

**Issue by bosszepro** [filoghost/ChestCommands#176]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Hello!
I would like to do a GUI who teleport the player to an other bungeecord server.
When I clic, on it, the server do nothing.

### How to reproduce

1.Take the example.yml file
2. Replace the line : COMMAND: -"op: spawn" by   ACTIONS:
    - 'server: lobby'
3. The plugin won't teleport u

### Server version

git-Spigot-db6de12-18fbb24 (MC: 1.8.8)

### Chest Commands version

3.1.4

**Comment by filoghost** [comment]
Please update to the latest version (v4+). Also make sure you're connected through BungeeCord too, or it won't work.
