### ISSUE TITLE
No me deja usar el plugin

### ISSUE THREAD

**Issue by folopoTW** [filoghost/ChestCommands#178]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Cuando pongo el plugin o uso un comando de el no me deja y me tira error

### How to reproduce

1 pongo el plugin
2 no me deja poner ningun comando del plugin

### Server version

1.17.1

### Chest Commands version

4.0.3

**Comment by filoghost** [comment]
Write in english please. If you have an error post it.
