### ISSUE TITLE
Placeholders dont work

### ISSUE THREAD

**Issue by iTroodon** [filoghost/ChestCommands#180]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [ ] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

The placeholder Pinger of placeholderapi dont work or dont show the variable

The extension is upload and I do /papi reload but it still dont working

### How to reproduce

all the expansion of placeholder of papi  dont work

### Server version

1.8.8 bukkit-r0.1-Snapshot

### Chest Commands version

3.1.4

### Additional information

![image](https://user-images.githubusercontent.com/109700752/180088224-d1211f08-0f61-40ec-80ce-2f9467f83221.png)
![image](https://user-images.githubusercontent.com/109700752/180088239-a68302ca-4b81-4689-8f5f-f1aee5b49a8d.png)

**Comment by filoghost** [comment]
Please update to the latest version (v4+), they do not exist in v3.
