### ISSUE TITLE
ID:402 Firework_Charge does not support NBT color

### ISSUE THREAD

**Issue by dv888** [filoghost/ChestCommands#181]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Please allow NBT-DATA toward Firework_Charge such as   NBT-DATA: '{Explosion:{Type:0b,Colors:[I;2651799]}}'

### How to reproduce

  ID: 402
  NBT-DATA: '{Explosion:{Type:0b,Colors:[I;2651799]}}'
  POINTS: 29
  COMMAND: 'op:irl give 1 {player}
  NAME: 'Free Firework charge'
  POSITION-X: 1
  POSITION-Y: 1

### Server version

1.8.8 PaperSpigot

### Chest Commands version

3.2.0

### Additional information

Why chestcommands does not support colored firework charge? This is not fair!

**Comment by filoghost** [comment]
Anything that works with the vanilla /give command also works in Chest Commands. The syntax you're using might be wrong or outdated.
