### ISSUE TITLE
Can i add a cooldown in commands?

### ISSUE THREAD

**Issue by Slime1207** [filoghost/ChestCommands#182]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

Can I add a cooldown time for actions? (BTW i cant see any about cooldown in FAQ and Documentation)

formatting-codes:
  MATERIAL: paper
  POSITION-X: 1
  POSITION-Y: 2
  NAME: '&dFormatting codes'
  LORE:
    - 'You can use all the formatting codes!'
    - 'Colors: &c#c &a#a &9#9 &e#e &f... ...'
    - 'Random (#k): &kexample'
    - 'Bold (#l): &lexample'
    - 'Strikethrough (#m): &mexample'
    - 'Underline (#n): &nexample'
    - 'Italic (#o): &oexample'
   Cooldown: 8s

### Chest Commands version

4.0.3

**Comment by filoghost** [comment]
No sorry, you will have to rely on a third-party plugin for cooldowns.
