### ISSUE TITLE
Potion ID usage

### ISSUE THREAD

**Issue by ElTioRodri** [filoghost/ChestCommands#183]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

What is the correct use of potion IDs in the materials?
example: potion (yes)
but:
vight_vision_potion (no)

(I don't know much about plugins)

### Chest Commands version

ChestCommands version 4.0.3

### Additional information

The icon "pocionVisionNocturna" in the menu "menu/doloresd.yml" has an invalid attribute "MATERIAL": unknown material "night_vision_potion".

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
