### ISSUE TITLE
Plugin not registering menu commands

### ISSUE THREAD

**Issue by lynrayy** [filoghost/ChestCommands#184]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Chestcommands not registering menu commands, and command looks like it is wrong (red) 
![image](https://user-images.githubusercontent.com/59417884/204291834-dd70ffd5-cd37-48fe-ba37-6225e405edf2.png)

### How to reproduce

1. create any menu
2. set any command in  ```
 # OPTIONAL
  # Set which commands a player can execute to open the menu.
  commands:
  - 'menu'
```
3. it is red 
![image](https://user-images.githubusercontent.com/59417884/204291956-fe5225f2-5ddc-4646-9f85-c5820f43f04a.png)


### Server version

This server is running Paper version git-Paper-290 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: d98c370)

### Chest Commands version

ChestCommands version 4.0.3

### Additional information

_No response_

**Comment by filoghost** [comment]
Unfortunately commands are registered dynamically, so the server previews them as invalid.

**Comment by lynrayy** [comment]
it is possible to register commands while server working. Just add this feature to your plugin.

**Comment by filoghost** [comment]
I don't think it's possible without touching Bukkit internal classes. Besides, the plugin is now in maintenance-only mode as I don't have the free time and passion I had some years ago.
