### ISSUE TITLE
I can't use BungeeCord's cross-server Commands in ChestCommands

### ISSUE THREAD

**Issue by orangezsclite** [filoghost/ChestCommands#186]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

English：
I can't use BungeeCord's cross-server Commands in ChestCommands!
i use some tools to edit cc's menu config file.
and today, i use that tools to edit Cross-server menu
and i input BC's /server [id] command in config
chat bar only says : "Commands Not Found."
How can i do?
(pls forgive my terrible english cuz im Chinese)
(All written configurations are at Additional information)
Tips: There is Server id : bw, sw, practice, sc

Chinese中文:
我不能在ChestCommands中使用Bungeecord的跨服指令！
我经常使用一些工具来编辑CC的菜单配置文件。
今天，我用工具去编辑跨服菜单
然后我输入了BC的跨服指令
聊天栏只会显示：未知的命令。
我该怎么办？
提示：服务器id有bw sw practice sc

### Chest Commands version

Latest version (tried to update)

### Additional information

[https://pastebin.com/h5imhCck](Pastebin)

**Comment by AxeWizard** [comment]
Use :
ACTIONS:
- 'server: <target>'

like :
- 'server: sc'

**Comment by filoghost** [comment]
The example above is the correct solution.
