### ISSUE TITLE
The language system of ChestCommands(Version-4.0.3) are Invalid

### ISSUE THREAD

**Issue by PreGrafer** [filoghost/ChestCommands#187]
### Description

I notice that the language system of ChestCommands(**Version-4.0.3**) are **Invalid**, it means i can't customize some tips.
also, can you add a switch for such 'Opening the menu xxx.yml.'
I think the language system of **Version-3.3.1** is great and easy-to-use. Wish u **re-add** it in the next version.

Best wishes.

**Comment by PreGrafer** [comment]
@filoghost are u here

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.

**Comment by PreGrafer** [comment]
Okay, thank you very much for taking the time to answer me

**Comment by PreGrafer** [comment]
> Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.

Okay, thank you very much for taking the time to answer me
