### ISSUE TITLE
MATERIAL: stone:1 doesn't work on 1.12.2

### ISSUE THREAD

**Issue by rebarakuk** [filoghost/ChestCommands#189]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

It also doesn't work:

  MATERIAL: stone
    NBT-DATA: '{Item:{id:"minecraft:stone",Damage:1}}'
    POSITION-X: 5
    POSITION-Y: 1
    NAME: ''

both of the cases just show stone, not granite

### How to reproduce

-

### Server version

This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Chest Commands version

ChestCommands version 4.0.3

**Comment by filoghost** [comment]
Use `DURABILITY: 1` instead.
