### ISSUE TITLE
Permissions doesnt works

### ISSUE THREAD

**Issue by lKhyst** [filoghost/ChestCommands#19]
I can't give permissions to acess the menu, I tried a lot of permissions styles and nothing. What could be?

Version of Server: Spigot 1.8.8 R01SNAPSHOT
CC Version: PAPI Supprot, the last one, I guess.

Permissions nodes:
https://pastebin.com/a016Km9X

My example.yml:
https://pastebin.com/kQ1LjpsF

Dont care about the language, its Portuguese from Brazil.

**Comment by Csoii** [comment]
The proper permission node is chestcommands.open.example.yml
