### ISSUE TITLE
Console Error on my server

### ISSUE THREAD

**Issue by HelpAStranger** [filoghost/ChestCommands#190]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Thats the only thing that appear, and only sometimes, but flooding it entirely 

[ChestCommands] Task #75 for ChestCommands v4.0.4 generated an exception
java.lang.ClassCastException: null

### How to reproduce

Just using the plugin normaly as always

### Server version

Mohist 1.16.5

### Chest Commands version

4.0.4

**Comment by filoghost** [comment]
Need the full error
