### ISSUE TITLE
This's most likely the same type of bug that is on all CatServer.

### ISSUE THREAD

**Issue by XY-chenm** [filoghost/ChestCommands#191]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Can steal button objects from menus (maybe the core problem?) 

### How to reproduce

1. Open any Chestcommands menu.
2. keep openning, select the item on the button you want to steal.
3. Then left-click on it and press the number key 1 at very, very fast speed (make sure there is nothing else in the inventory corresponding to your number key 1).
4. Finally, you'll see that the button on the menu has been buttoned down.

### Server version

This server is running CatServer version git-CatServer-1.12.2-fed56812 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)

### Chest Commands version

ChestCommands version 4.0.4

**Comment by XY-chenm** [comment]
My bad I think should be asked to CatServer authors,but I'm not sure if it's the plugin itself.

**Comment by filoghost** [comment]
Does Spigot have this bug?
