### ISSUE TITLE
Player failed to use command and it prompts ChestCommands v4.0.5 - plugin is disabled but i cant understand know what is wrong

### ISSUE THREAD

**Issue by Rebines** [filoghost/ChestCommands#194]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

Today i entered my server and needed to teleport to the loby then i tried to open the main menu but it is failed the it prompts ChestCommands v4.0.5 - plugin is disabled
![image](https://github.com/filoghost/ChestCommands/assets/97930336/99fa51c0-5689-47cc-a362-eecceadb8e3f)

### How to reproduce

1.Around 2 weeks ago i use it teleported myself to another world and created tings for video with my friends who is another administrater of my server
2.I enabled command-block in server.properties and left the server without teleporting
3.Today I found the bug and disabled command-bloc but it doesnt work

### Server version

This server is running Paper version git-Paper-68 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 5de0f8a) You are 128 version(s) behind Download the new version at: https://papermc.io/downloads/paper

### Chest Commands version

This server is not running any plugin by that name

**Comment by filoghost** [comment]
I need the startup log. Something went wrong during the initialization.

**Comment by Rebines** [comment]
sorry ,no enough memory
