### ISSUE TITLE
problem with lapis lazuli

### ISSUE THREAD

**Issue by jamoreq** [filoghost/ChestCommands#22]
Hey, i'm trying to do chest shop , but i can't sell lapis lazuli

step : required-item : dye:4

and in game , when i'm clicking on sell , he call me "u need to have 1 Ink Sac to do that"

this way doesn't work with all "dye:"

An issue possible ?

**Comment by filoghost** [comment]
Sorry if I answer so late. Do you still have this problem? What Spigot version are you using? Please post your menu configuration.

**Comment by darksitegamers** [comment]
Maybe try the code 
      Required-item: 351:4

Im not sure if its : or ; or ,
