### ISSUE TITLE
Running a command as OP not working

### ISSUE THREAD

**Issue by treydun** [filoghost/ChestCommands#23]
Setting the format COMMAND: 'op: somecommand' is resulting in that being run in the console instead of running the command as OP

[19:31:48 INFO]: > Treydun issued server command: /op: somecommand

Same thing happens with no space. COMMAND: 'op:somecommand'
[19:32:41 INFO]: > Treydun issued server command: /op:somecommand

**Comment by filoghost** [comment]
Sorry if I only answer now. If you still have the problem, what server version are you using? Are you using the latest version of Chest Commands?
