### ISSUE TITLE
Skull Owner problem

### ISSUE THREAD

**Issue by Blacki017** [filoghost/ChestCommands#24]
Hello,
I have a problem with the display of heads, indeed I downloaded the latest version of the plugin and my problem is that when I put a SKULL-OWNER, if I put a player it works but the variable 'player' does not work.
A solution to that?

> tete:
>   NAME: '&a&l{player}'
>   ID: player head
>   SKULL-OWNER: '{player}'
>   KEEP-OPEN: true
>   POSITION-X: 5
>   POSITION-Y: 1

**Comment by filoghost** [comment]
Use the latest development version: https://ci.codemc.io/job/filoghost/job/ChestCommands/

It supports variable in the SKULL-OWNER property.
