### ISSUE TITLE
Can't put placeholders in NBT-DATA

### ISSUE THREAD

**Issue by soshimee** [filoghost/ChestCommands#26]
If I do NBT-DATA: '{SkullOwner:{player}}' or NBT-DATA: '{SkullOwner:"{player}"}', it thinks the {player} part is literally a player called "{player}". but I want it to be a placeholder. any solutions?

**Comment by filoghost** [comment]
Sorry, you can't use placeholders there. However, you can use `SKULL-OWNER: '{player}'` to achieve that effect.
