### ISSUE TITLE
Dependency Conflict: duplicate classes "com.google.gson.stream.JsonReader.nextInt" in different JARs, have different implementations

### ISSUE THREAD

**Issue by HelloCoCooo** [filoghost/ChestCommands#28]
Hi, in **ChestCommands/Plugin**, duplicate classes with the same fully-qualified name **com.google.gson.stream.JsonReader.nextInt** are included in two different libraries, i.e., **me.clip:placeholderapi:2.9.2** and **com.google.code.gson:gson:2.2.4**.

According to *"first declaration wins"* class loading strategy, only this class in **com.google.code.gson:gson:2.2.4** can be loaded, and that in **me.clip:placeholderapi:2.9.2** will be shadowed.

By further analyzing, your project expects to invoke method **com.google.gson.stream.JsonReader.nextInt** in **me.clip:placeholderapi:2.9.2**. As it has been shadowed, so that this method defined in **com.google.code.gson:gson:2.2.4** are actually forced to be referenced via the following invocation path:

```
<com.gmail.filoghost.chestcommands.config.AsciiPlaceholders: placeholdersToSymbols(Ljava/lang/String;)Ljava/lang/String;> /root/sensor/unzip/ChestCommands-master/Plugin/target/classes
<com.google.gson.JsonStreamParser: next()Ljava/lang/Object;> /root/.m2/repository/me/clip/placeholderapi/2.9.2/placeholderapi-2.9.2.jar
<com.google.gson.JsonStreamParser: next()Lcom/google/gson/JsonElement;> /root/.m2/repository/me/clip/placeholderapi/2.9.2/placeholderapi-2.9.2.jar
<com.google.gson.internal.Streams: parse(Lcom/google/gson/stream/JsonReader;)Lcom/google/gson/JsonElement;> /root/.m2/repository/me/clip/placeholderapi/2.9.2/placeholderapi-2.9.2.jar
<com.google.gson.internal.bind.TypeAdapters$7: read(Lcom/google/gson/stream/JsonReader;)Ljava/lang/Object;> /root/.m2/repository/me/clip/placeholderapi/2.9.2/placeholderapi-2.9.2.jar
<com.google.gson.internal.bind.TypeAdapters$7: read(Lcom/google/gson/stream/JsonReader;)Ljava/lang/Number;> /root/.m2/repository/me/clip/placeholderapi/2.9.2/placeholderapi-2.9.2.jar
<com.google.gson.stream.JsonReader: nextInt()I>
```

**Workaround solution:**
An easy way to workaround the problem is **reversing the declaration order** of these two libraries (i.e., reverse the declaration order of httpclient and maven-resolver-transport-http) in pom file.
Then, according to **"first declaration wins"** class loading strategy, class **com.google.gson.stream.JsonReader.nextInt** in **me.clip:placeholderapi:2.9.2** can be loaded (the version that **ChestCommands/Plugin** expects to reference by static analysis).
This fix will not affect other libraries or class, except the above duplicate class.

### Dependency tree---

[INFO] com.gmail.filoghost.chestcommands:chestcommands-plugin:jar:3.3.0-SNAPSHOT
[INFO] +- org.spigotmc:spigot-api:jar:1.8.8-R0.1-SNAPSHOT:provided
[INFO] |  +- commons-lang:commons-lang:jar:2.6:provided
[INFO] |  +- com.googlecode.json-simple:json-simple:jar:1.1.1:provided
[INFO] |  |  \- junit:junit:jar:4.10:provided
[INFO] |  |     \- org.hamcrest:hamcrest-core:jar:1.1:provided
[INFO] |  +- com.google.guava:guava:jar:17.0:provided
[INFO] |  +- **com.google.code.gson:gson:jar:2.2.4:provided**
[INFO] |  +- org.avaje:ebean:jar:2.8.1:provided
[INFO] |  |  \- javax.persistence:persistence-api:jar:1.0:provided
[INFO] |  +- org.yaml:snakeyaml:jar:1.15:provided
[INFO] |  \- net.md-5:bungeecord-chat:jar:1.8-SNAPSHOT:provided
[INFO] +- net.milkbowl.vault:VaultAPI:jar:1.6:provided
[INFO] |  \- org.bukkit:bukkit:jar:1.9-R0.1-SNAPSHOT:provided
[INFO] +- me.confuser:BarAPI:jar:3.5:provided
[INFO] +- **me.clip:placeholderapi:jar:2.9.2:provided**
[INFO] \- org.bstats:bstats-bukkit-lite:jar:1.4:compile

Thank you very much.
Best,
Coco

**Comment by HelloCoCooo** [comment]
Code snippet of **com.google.gson.stream.JsonReader.nextInt** in **me.clip:placeholderapi:2.9.2**  (shadowed but expected to invoke method):

```java
//line 870
if (p == 16) {
  this.peekedString = new String(this.buffer, this.pos, this.peekedNumberLength);
  this.pos += this.peekedNumberLength;
} else if (p == 8 || p == 9 || p == 10) {
  if (p == 10) {
    this.peekedString = nextUnquotedValue();
  } else {
    this.peekedString = nextQuotedValue((p == 8) ? 39 : 34);
  } 
  try {
    int result = Integer.parseInt(this.peekedString);
    this.peeked = 0;
    this.pathIndices[this.stackSize - 1] = this.pathIndices[this.stackSize - 1] + 1;
    return result;
  } catch (NumberFormatException numberFormatException) {}
}
```



Code snippet of **com.google.gson.stream.JsonReader.nextInt** in **com.google.code.gson:gson:2.2.4** (loaded version):

```java
//line 841
if (p == 16) {
  this.peekedString = new String(this.buffer, this.pos, this.peekedNumberLength);
  this.pos += this.peekedNumberLength;
} else {
  if (p != 8 && p != 9) {
    throw new IllegalStateException("Expected an int but was " + this.peek() + " at line " + this.getLineNumber() + " column " + this.getColumnNumber());
  }

  this.peekedString = this.nextQuotedValue((char)(p == 8 ? '\'' : '"'));

  try {
    result = Integer.parseInt(this.peekedString);
    this.peeked = 0;
    return result;
  } catch (NumberFormatException var5) {
  }
}

```



As a result, these conflicting method included in **me.clip:placeholderapi:2.9.2** deals with different cases, which changes the control flows and data flows. So being forced to use these methods in **com.google.code.gson:gson:2.2.4** may lead to inconsisitent semantic behaviors.

**Comment by HelloCoCooo** [comment]
@filoghost May I pull a request to fix it?

**Comment by filoghost** [comment]
Hello, thank you very much for the in-depth analysis, sorry if I only answer now. I think it's quite bad that PlaceholderAPI includes a common library, especially one that already ships with Spigot, without relocating it.

However, I don't understand why is this dependency order important, since ChestCommands doesn't call `com.google.gson.stream.JsonReader.nextInt` (the method you mentioned). The dependency order is not important during runtime (it will not affect class loading). Is it relevant only for other plugins using ChestCommands through Maven?
