### ISSUE TITLE
Multiple REQUIRED ITEM bug

### ISSUE THREAD

**Issue by s1birsky** [filoghost/ChestCommands#30]
please help

I'm trying to enter multiple required items:

REQUIRED-ITEM: 'iron_ingot, 3; emerald, 5; stick, 2'

But in console I get errors like:

The icon "melon" in the menu "eda.yml" has an invalid REQUIRED-ITEM: invalid amount "3;emerald"

It thinks that emeralds is the part of the ingots amount. And no matter what I type in I see the same kind of error. Everything's OK only when I enter 1 item but that not works for me. Maybe there's something wrong with the syntax? How do I make multiple required items? Last version 3.2.0 
Minecraft 1.14.4

**Comment by Spirious111** [comment]
Hello, put this 

Iron:
    REQUIRED-ITEM: 'Iron ingot, 3'
    COMMAND: 'give-money: 8'

    NAME: '&6&lVendre : &e&lMinerais de fer &a&lx1 &6&lpour &a&l8$'
    ID: 265
    POSITION-X: 4
    POSITION-Y: 1
=)

**Comment by filoghost** [comment]
You were using a version that didn't have that feature. Please check out the 3.3.0 update.
