### ISSUE TITLE
multiple item in the GUI 

### ISSUE THREAD

**Issue by Spirious111** [filoghost/ChestCommands#31]
Hello, i want to sell x32 diamonds in my shop so i entered 
Diamond:
    REQUIRED-ITEM: 'Diamond, 32'
    COMMAND: 'give-money: 800'

    NAME: '&6&lVendre : &e&lDiamant &a&lx32 &6&lpour &a&l800$'
    ID: 264
    POSITION-X: 3
    POSITION-Y: 2
all good for this,

But i want the players to see 32 diamonds for the icon of the GUI how can i make that ? thanks =)

**Comment by i9hdkill** [comment]
Add
```AMOUNT: XX```
