### ISSUE TITLE
Firework color?

### ISSUE THREAD

**Issue by Dark-LYNN** [filoghost/ChestCommands#33]
Hey im the creator of the discord someone asked this question and didmt wanne go on github to ask it the Question : 
`I have a question, for example, if I want to change the color of a firework star, do I have to use NBT-DATA? because I was testing the options including that one and none gives me the result I am looking for. Or is it that I have to use a special map for fireworks stars?`

( the menu config )

```
*heal:
NAME: '&d&l/heal'
LORE:
- '&f► &7Comando para curarte, ademas de'
- '&f  &7alimentarte'
ID: potion
NBT-DATA: {Potion: "minecraft:healing"}
POSITION-X: 8
POSITION-Y: 3*
 
POSITION-Y: 3*
```

(No errors in console)

```
I read at least an hour of potions NBT-DATA, I tried everything from numeric id to legacy id, and nothing works for me, I also tried putting POTION: "potion name"
 And I couldn't either, I tried DATA-VALUE and I didn't succeed either.
```

**Comment by filoghost** [comment]
The answer is yes, they need to use NBT-DATA. I'm not providing for NBT though, there are some "/give" command generators and other resources that can be used to generate the correct value. The rule of thumb is that if it works with the /give command, it should also work with NBT-DATA.
