### ISSUE TITLE
Is there a way to put UTF-8?

### ISSUE THREAD

**Issue by djonibourscheid** [filoghost/ChestCommands#34]
### What are you trying to do?

. - / -

### What have you tried so far?

. - / -

### Platform

- Server version (output of `/version`): Spigot 1.8 R0.1-SNAPSHOT
- Chest Commands version (check with `/cc`):  3.3.0

### Additional context

I am Brazilian and I wanted to leave the texts in UTF-8 to accentuate them correctly, however, when I put them in UTF-8 format, it does not work. Is there any way I can do this? Otherwise, do you plan to add support for UTF-8?

Sorry if the typing is strange, translated by Google Translate

**Comment by filoghost** [comment]
You need to save the file in UTF-8 with your text editor. Chest Commands can already read files in UTF-8.
