### ISSUE TITLE
Template/fill items

### ISSUE THREAD

**Issue by dmitriJ2101** [filoghost/ChestCommands#35]
Hello, why don't you make a function that allows you to set the standard value of the item in the gui, if the cell is not configured, the standard item will be used.
IMAGE EXAMPLE: http://skrinshoter.ru/s/020620/nsUkguTU

**Comment by filoghost** [comment]
What would be a use case for this?

**Comment by dmitriJ2101** [comment]
http://skrinshoter.ru/s/030620/eMU5xOAj

**Comment by filoghost** [comment]
Same as this one then? https://github.com/filoghost/ChestCommands/issues/36

I think the two features can be combined. Instead of a default icon, a "templates" section can be added (maybe even with a "global-templates.yml" config file). Then in the menu settings you just specify a template to fill the void space.

**Comment by dmitriJ2101** [comment]
I think the template elements will be superfluous

**Comment by ItzKarsten06** [comment]
how do i set planks in a menu as material

**Comment by AfkF24** [comment]
I think this would be **very** welcome to have.
Perhaps items that should be displayed on multiple slots shouldn't be using `POSITION-X` and `POSITION-Y`, but rather `SLOTS`. For example:
```
fill-item:
  MATERIAL: white_stained_glass_pane
  SLOTS: 1-3,5,7-9,10-18
  KEEP-OPEN: true
```
What this would do is basically have the item set on slots 1-3, 5, 7-9 in the first GUI row, and across the whole 2nd GUI row.

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
