### ISSUE TITLE
enchantments?

### ISSUE THREAD

**Issue by Dark-LYNN** [filoghost/ChestCommands#37]
hey I have a question on my server i created a shop with chestcommands
and i want peaple to buy enchantment books but if i do

> COMMAND: 'give: enchanted_book,1, enchant: Sharpness|1 DAMAGE_ALL|1'
it dont work it just gives an empty enchantment book

and i cant find the MATERIAL in  the bukkit list {[link](https://hub.spigotmc.org/javadocs/spigot/overview-summary.html)}

**Comment by filoghost** [comment]
That's not the correct format. The material is correct, but the `give:` action doesn't support enchantments. You need to use the vanilla `give` command from the console.

Example:
```
COMMAND: 'console: give {player} ...'
```
