### ISSUE TITLE
"Player not found" trying to make a Protection Stones store

### ISSUE THREAD

**Issue by Gohansuperd** [filoghost/ChestCommands#45]
### What are you trying to do?

I am trying to make a protection store following a tutorial, but due to the changes in the plugin it doesn't work anymore.
The operation is that with the action "console: ps give 20x20 (player)" of the item to the player since (player) should interpret it as the name of the player who executes the command. But what happens to me is that when using this it gives the error in the console: Player not found ((player)) (Referring to the fact that "(player)" does not interpret it as the name of the player, instead of that take it as giving protection to the player "(player)")

### What have you tried so far?

I've only tried changing the (player) to% player% for the placeholder. But the plugin kept interpreting this as that is the player's name.

### Platform

- Server version (output of `/version`): 
- Chest Commands version (check with `/cc`): 
Server version: 1.14.4
Chest Commands version: 3.3.0

### Additional context

Sorry if it sounds weird but it's because the translator is not 100% accurate.

**Comment by filoghost** [comment]
It's `{player}`

**Comment by Gohansuperd** [comment]
Thanks so much!
