### ISSUE TITLE
Can't make PlaceholderAPI working with item descriptions

### ISSUE THREAD

**Issue by DotDebian** [filoghost/ChestCommands#46]
### Description
Using latest ChestCommand and PlaceholderAPI, I cannot use PAPI placeholders in items descriptions.

### How to reproduce
Use latest ChestCommand and PlaceholderAPI versions, create a GUI and put the placeholder of PlayerPoints (for example). It's not parsing the placeholder at all. /papi parse %playerpoints_points% Nickname does parse it to 0 tho.

### Platform
- Server version (output of `/version`): 
PaperSpigot 1.8.8-R0.1-Snapshot
- Chest Commands version (check with `/cc`): 
3.3.1

### Additional context
![image](https://user-images.githubusercontent.com/20359522/84837337-25f9b380-b038-11ea-8bec-fa6fcb2e202c.png)
![image](https://user-images.githubusercontent.com/20359522/84837354-2eea8500-b038-11ea-9be9-0539eaf629bc.png)

**Comment by DotDebian** [comment]
I found out I was simply not using the correct pattern for placeholders. Clarifying the documentation about this would be great.

**Comment by filoghost** [comment]
I mean, the documentation states that PlaceholderAPI is supported. If you go to the PlaceholderAPI documentation, you can find a list of supported placeholders (with the correct format). Should I note that it uses a different format (`%...%` instead of `{...}`)?
