### ISSUE TITLE
support for the PlayerPoints plugin

### ISSUE THREAD

**Issue by Cosmoz3255** [filoghost/ChestCommands#48]
### What are you trying to do?
why removed support for this plugin, please return, I have the entire system was spun on these two plugins

### Platform

- Server version (output of `/version`): 
- Chest Commands version (check with `/cc`):

**Comment by filoghost** [comment]
PlayerPoints is not maintained anymore since 2016, that's the reason support was dropped. I don't know what people use these days, but there probably are modern alternatives.

**Comment by GabrielCorrent** [comment]
PlayerPoints is alive!
https://www.spigotmc.org/resources/playerpoints.80745/
