### ISSUE TITLE
Namespace Support

### ISSUE THREAD

**Issue by UltraBlackLinux** [filoghost/ChestCommands#49]
### Description

Please add support for namspaces in mods, cause Im using Magma and I need some modded textures, but with out namespace it doesnt accept the Icon, propably not even the buy functionality
Id love to see this in yor great plugin,
Thanks!

**Comment by filoghost** [comment]
I honestly don't know anything about Magma and mods. I assume mods don't add new Material(s), since the class is an enum. If anyone is willing to explore solutions, I'm open to pull requests, but I can't officially support anything other than Spigot at the moment.

**Comment by UltraBlackLinux** [comment]
oof, ok thanks for the response!
