### ISSUE TITLE
1.16 Hexcode support

### ISSUE THREAD

**Issue by pacificminer** [filoghost/ChestCommands#52]
### Description
Please add support for 1.16 Hexcode colors. Currently limited to the traditional old 12 or so colors. Hexcode support would be awesome.

**Comment by pacificminer** [comment]
@filoghost

**Comment by filoghost** [comment]
I need to decide on a format that is simple and easy to use. Probably &#00ff00, &(00ff00) or &<00ff00>. I also need to check if other plugins have adopted a standard format.

**Comment by filoghost** [comment]
A note: you can already use hex codes, although the default format is a bit impratictal: the color `#00ff00` becomes `&x&0&0&f&f&0&0` (the &x is what determines the start of the hex code)

**Comment by filoghost** [comment]
This is now present in v4.0.3.
