### ISSUE TITLE
Skull-Owner

### ISSUE THREAD

**Issue by mehdi200510** [filoghost/ChestCommands#54]
### What are you trying to do?
I want to put the head of the guy who opens the menu (his skin)

### What have you tried so far?
![image](https://user-images.githubusercontent.com/68790490/88465119-9f4eb680-cec0-11ea-9478-542bcd7fc586.png)
i put that in my config

### Platform

- Server version (output of `/version`): 1.8.8
- Chest Commands version (check with `/cc`): 3.1.4

### Additional context
  
  ID: head
  DATA-VALUE: 3
  SKULL-OWNER: '{player}'
  KEEP-OPEN: true

**Comment by filoghost** [comment]
Update the plugin and it will work.
