### ISSUE TITLE
Perms don't want to work

### ISSUE THREAD

**Issue by jamezburritos** [filoghost/ChestCommands#56]
### Description
When I try to open my Kits menu with a Totem of Undying, the plugin tells me that I'm missing the chestcommands.open.Kits.yml permission. This started happening after I integrated BungeeCord to my 1.16.1 server. I have tried all varieties of the chestcommands. permissions including chestcommands.*. It is part of the default permset.

### How to reproduce
Right click on the Totem of Undying in your hotbar. There is an error saying that you don't have the correct permissions.

### Platform

- Server version (output of `/version`): This server is running CraftBukkit version git-Spigot-4d9262c-dc7c3c6 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
- Chest Commands version (check with `/cc`): 3.3.1

**Comment by filoghost** [comment]
Does it only happens with a totem of undying? Do other items work?
