### ISSUE TITLE
Readd use-only-commands-without-args setting

### ISSUE THREAD

**Issue by Kakifrucht** [filoghost/ChestCommands#63]
### Description

I guess this will be shot down, because you probably removed it due to architectural changes with handling commands, but I found it quite useful for a warp menu. When players just type /warp, open the menu, if they add a argument let the /warp plugin handle that. If it is indeed trivial to add back it would be much appreciated. Other than that thanks for the support, the conversion has worked perfectly fine!

**Comment by filoghost** [comment]
It was removed because I planned to eventually re-add it later, if requested, but on a per-menu basis. Consider it accepted for the future.

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
