### ISSUE TITLE
Suggestion to add "close-actions" to the list of options on menu

### ISSUE THREAD

**Issue by Corazun** [filoghost/ChestCommands#66]
### Description

Hello, I think adding a close-actions list working like open-actions but on inventory close could be really nice (especially if you want to add/remove permissions on menu open/close)

**Comment by filoghost** [comment]
I don't know if it is detectable. Adding permissions in open-actions and removing them in close-actions sounds like a really bad idea. Any player with a modified client could execute arbitrary commands while the menu is open, not just the ones inside the menu.

**Comment by Corazun** [comment]
Well you have the ``InventoryCloseEvent`` to detect it, in fact i'm just adding the permission to my players to use /repair inside the menu with a button that execute the command, and would like to remove the permission after they closed the inv. I'm forced to used that cause the repair plugin what I found when is executed with op rights isn't taking money from player's bank account...

**Comment by filoghost** [comment]
Sorry but I won't be implementing this; it's very specific to your use case, and not something that would help many users. Even in your case, it could be detrimental, as it's not reliable: if the server is restarted or crashes when a player has the the menu open, the permission will stay.

Some options:
* Can you just give them the permission to repair?
* Can you give and remove the permission inside the icon ACTIONS? (you have 3 actions: one to add the permission, one to use the command, and the last one to remove it)
