### ISSUE TITLE
Enchanted Golden Apple

### ISSUE THREAD

**Issue by Heaved** [filoghost/ChestCommands#67]
### What are you trying to do?
< Help request >

### What have you tried so far?
<i tried to add enchanted golden apple to materials but i can't it Says error>

### Platform

- Server version (output of `/version`): 1.8.8
- Chest Commands version (check with `/cc`): 4.0.2

### Additional context
<economy-take:
  MATERIAL: enchanted golden apple
  POSITION-X: 3
  POSITION-Y: 1
  NAME: '&dEnchanted Golden Apple'
  LORE:
    - '&fTrade &e1 Gold Ingot &fFor &d1 Enchanted Golden Apple'
  REQUIRED-ITEMS:
    - gold ingot>

**Comment by Corazun** [comment]
``enchanted golden apple`` doesn't exist in 1.8, it's ``golden apple`` with the durability ``1``, ``0`` is for the normal golden apple. So update with ``MATERIAL: golden apple`` and below ``DURABILITY: 1``

**Comment by filoghost** [comment]
Thanks @Corazun. I've added the materials list for each version on the documentation, for 1.8 it's https://helpch.at/docs/1.8/org/bukkit/Material.html.
