### ISSUE TITLE
I can't remove the message 'opening the menu {name}.yml '

### ISSUE THREAD

**Issue by Pulsih** [filoghost/ChestCommands#71]
### What are you trying to do?

Remove the message 'opening the menu {name}.yml '

### What have you tried so far?

I search in the config.yml lang.yml and placeholders.yml but THER'S NO MORE THE STRING in the config.yml opening-menu: 'opening menu {name}.yml'

### Platform

- Server version (output of `/version`): 
- Chest Commands version (check with `/cc`): 
Server verison: 1.16.4
Plugin version: 4.0.3
![2020-11-07_23 01 40](https://user-images.githubusercontent.com/74119488/98453222-bacb8d80-214e-11eb-8b1f-d1abfe7796ba.png)

**Comment by filoghost** [comment]
Did you solve the issue or did you give up?

**Comment by Pulsih** [comment]
I find an alternative way to open othet gui
