### ISSUE TITLE
Give Enchanted Items

### ISSUE THREAD

**Issue by Heaved** [filoghost/ChestCommands#72]
### What are you trying to do?
<Give Players Enchanted Items>

### What have you tried so far?
<- 'give: @p diamond_helmet 1 0 {ench:[{id:17,lvl:2}]}'>

### Platform

- Server version (1.8.8): 
- Chest Commands version (4.0.3): 

### Additional context
<economy-take:
  MATERIAL: 310
  POSITION-X: 3
  POSITION-Y: 2
  LORE:
    - '&r'
    - '&a&lCost'
    - '&75 Emerald'
    - '&r'
    - '&eClick To Purchase'
  REQUIRED-ITEMS:
    - emerald, 5
  ACTIONS:
    - 'tell:&cREDPVP &7| &7You have purchased an item'
    - 'give: @p diamond_helmet 1 0 {ench:[{id:17,lvl:2}]}'
  KEEP-OPEN: true>

**Comment by filoghost** [comment]
That's not how you should use the `give` action: either use the format specified in the wiki, or use `console: give {player} diamond_helmet 1 0 {ench:[{id:17,lvl:2}]}` (a console command, which supports enchants)
