### ISSUE TITLE
When i try to open specific menu server gets drop for 2 secs

### ISSUE THREAD

**Issue by Inxity** [filoghost/ChestCommands#73]
### Description

When i run a menu i create server is drop spiking for 2 secs

### How to reproduce

Use the menu below
https://paste.md-5.net/iwukerofah.pl

### Platform

- Server version (output of `/version`): Paper 291 1.16.4
- Chest Commands version (check with `/cc`): 4.0.3 then tried 4.0.4 but problem still continues

### Additional context

Config
https://paste.md-5.net/ewehexupap.coffeescript

**Comment by filoghost** [comment]
Not caused by Chest Commands, I'm 99% sure. Some plugin may be listening to InventoryOpenEvent and creating lag. Try without other plugins, and please attach timings in case it's actually caused by Chest Commands (no need to open a new issue, reply here).
