### ISSUE TITLE
'Back to Achievements List' Button having a configurable command line/string run when clicked

### ISSUE THREAD

**Issue by TheCashFire** [filoghost/ChestCommands#78]
### Description
Adding a small subnode for the 'Back to Achievements List' button in the GUI, allowing us to give a command to be executed when that button is pressed and the user returns to the main menu. Would help immensely with custom GUI creation, as right now, a user can go in and see their achievements through a custom GUI but has to close the menu to reopen any external GUI. Just a small QOL. Thanks!

**Comment by filoghost** [comment]
You should add a back button manually. In the main menu you open the sub-menu, in the sub-menu you open the main menu.

**Comment by TheCashFire** [comment]
I'm terribly sorry, this was the wrong plugin I made an issue for. So sorry!
