### ISSUE TITLE
Commands Appear White When Typing

### ISSUE THREAD

**Issue by HisBoilingPoint** [filoghost/ChestCommands#80]
### Description

Currently, if users are typing the command associated with the menu (e.g. /ranks) the command they are entering will appear red as if the command doesn't exist. I don't know if it's possible to fix or it's just happening to me but ideally, the custom command would appear in white and have the tab auto-fill feature working.

**Comment by xNico7u7** [comment]
Hi, I have the same problem. Did you find a solution?

**Comment by HisBoilingPoint** [comment]
https://github.com/RLNT/spigot-registercommands

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
