### ISSUE TITLE
Ability to show different icon nodes depending on permission

### ISSUE THREAD

**Issue by andrewleppala** [filoghost/ChestCommands#82]
### Description

Add ability for two icons in the same position to show depending on permission. Currently, if two icons are in the same position and VIEW-PERMISSION is set with two permissions, a user with only one will see neither. Opped users appear to see the entry last placed for that position in the YML file for the menu. Users with the permission node which matches the lowest entry in the menu file for that particular position see expected behavior, with any conflicting permissions (such as rank1 and rank2 in my example) see no entries.

For example, say I have three entries in position 1,1, with VIEW-PERMISSION of:
myserver.rank1
myserver.rank2
myserver.rank3

I would like each icon to do different things depending on view-permission, so higher rank players receive new buttons, in the same location, in the same menu. This would allow server administrators to create more dynamic menus that can change for the player as they progress.

View from Rank1's perspective: [Rank1](https://andrews.fi/les/33e92.png)
View from Rank2's perspective: [Rank2](https://andrews.fi/les/b954e.png)
View from Rank3's perspective: [Rank3](https://andrews.fi/les/3ce83.png)
All of the tiles that Rank3 can currently see, should be viewable from Rank1 and Rank2, with different entries in the menu file, however this behavior is not observed.

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
