### ISSUE TITLE
I have a problem with the commands 😶

### ISSUE THREAD

**Issue by Jakineru** [filoghost/ChestCommands#86]
I just have a problem, I don't know what to say here, the important info is below 🖤

### What are you trying to do?

I am trying to open a menu with /menu

### What have you tried so far?

Restart the server several times, reinstall the plugin, revert to previous versions of spigot/plugin

### Platform

- Server version (output of `/version`): git-Spigot-37d799b-3eb7236 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Chest Commands version (check with `/cc`): 4.0.3

### Additional context

 I have the default plugin configuration (I was testing

**Comment by snnwer** [comment]
what does it say in the console & what's your code

**Comment by filoghost** [comment]
Please read the documentation about menus, more specifically the `commands` option: https://filoghost.me/docs/chest-commands/menus
