### ISSUE TITLE
Required-Items, adding data value/nbt-tag

### ISSUE THREAD

**Issue by oggimaster** [filoghost/ChestCommands#88]
### What are you trying to do?
I want to assign the item "enchanted_book" a data value "{StoredEnchantments:...}" in "REQUIRED-ITEMS" for item trading.

### What have you tried so far?
Using NBT-Tags: ENCHANTED_BOOK:{StoredEnchantments:[{id:"minecraft:efficiency", lvl: 5s}]}; adding "Tag" and '..'. The defined NBT-DATA interacts with the icon material only.

### Platform

- Server version (output of `/version`): git-Paper-366 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
- Chest Commands version (check with `/cc`): 4.0.3

**Comment by filoghost** [comment]
See #114, to avoid duplicate issues.
