### ISSUE TITLE
Menu BUG

### ISSUE THREAD

**Issue by Mimexe** [filoghost/ChestCommands#89]
### Description
When I click on the button to open a menu other than the current one, it doesn't open it.

### How to reproduce
/imenu > click on the diamond. (on my server)

### Platform

git-PaperSpigot-"4c7641d" (MC: 1.8.8)
3.1.4

**Comment by snnwer** [comment]
what's the code

**Comment by oggimaster** [comment]
You have to use this function:

  ACTIONS:
    **- 'open: imenu.yml'**
   
When you type it in as command like this:
 
  ACTIONS:
    - 'imenu'

, it doesnt overwrite the current shown menu. I think the code behind the "open:" function closes the current menu and then opens the targeted menu.

**Comment by filoghost** [comment]
Not enough details provided, but as oggimaster said you may be using the wrong action to open the menu.
