### ISSUE TITLE
Plugin crashes after server reload

### ISSUE THREAD

**Issue by VewixxPlayer** [filoghost/ChestCommands#92]
### Description

The plugins seems to work right when the server first starts, but crashes every time I reload.
### How to reproduce

I just installed ChestCommands, touched nothing about the plugin and reloaded.
### Platform

- Server version (output of `/version`):  This server is running CraftBukkit version 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Chest Commands version (check with `/cc`): 4.0.3

### Additional context

Haven't changed the configuration yet nor touched anything from the plugin.
If relevant, my additional plugins are ItemJoin, LuckPerms and Spawntp. Running on a Bungeecord network (plugin is only installed on individual server).
The error log is attached.
[crash_error.txt](https://github.com/filoghost/ChestCommands/files/5839343/crash_error.txt)

**Comment by Tomigames** [comment]
Don't reload the plugin

**Comment by filoghost** [comment]
Reloading with /reload is not supported: however the plugin detects it, but fails to log the message (because the logger is not initialized). Therefore this is a bug.

**Comment by filoghost** [comment]
Fixed in b90fa741c53dc1280a092d89801f06be16810998 and ab8bfc0a8b5e4f87851e646f8d24f166e8dd2314. The plugin will now be disabled with a descriptive error message if an external reload is detected.
