### ISSUE TITLE
Adding Placeholders to other parts of the config 

### ISSUE THREAD

**Issue by Tomigames** [filoghost/ChestCommands#96]
### Description

I would like to request the addition of being able to use placeholders on AMOUNT, DURABILITY and others section of the config. If this is already a feature I am sorry I have been unable to make it work.

**Comment by filoghost** [comment]
Sorry, I'm officially putting this plugin in maintenance-only mode. I already didn't have enough free time, I should have done it earlier. So I won't be adding new features.
