### ISSUE TITLE
Unbreakable items for custom textures

### ISSUE THREAD

**Issue by Naghell** [filoghost/ChestCommands#97]
### Description
Basically add a variable "unbreakable: true / false" to be able to place items w/ custom textures in menus. I already tried with the NBT but it doesn't work.

**Comment by filoghost** [comment]
NBT may be different depending on the server version, the NBT-DATA option works fine. Your NBT may be not be valid: the rule of thumb is that if it works with the vanilla /give command, it should work with NBT-DATA.
