### ISSUE TITLE
"Permission-Message" colour codes not working

### ISSUE THREAD

**Issue by TheClassic36** [filoghost/ChestCommands#98]
### Description
Creating an icon with a "permission-message" attribute with colour codes (e.g. "&a") will cause the message to appear in white in the chat - the colour codes are ignored.

### How to reproduce
1. Create a menu & an icon
2. Give the icon the "permission-message" attribute
3. Type a message with colour codes (e.g. "&eError! &7You do not have permission to do that!")
4. Reload ChestCommands
5. Open menu & click the icon (make sure you don't have permission first, so you see the message!)
6. Open chat - the message will be there in white.

### Platform
- Server version (output of `/version`): "Paper version git-Paper-465 (MC 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Chest Commands version (check with `/cc`): 4.0.3

### Additional context
Message in menu file:
https://i.imgur.com/UwEuTPk.png

How it displays in chat:
https://i.imgur.com/58d67kc.png

Example menu:
https://pastebin.com/8UCKR7ta

**Comment by filoghost** [comment]
Fixed in b90fa741c53dc1280a092d89801f06be16810998 (will be contained in the v4.0.4 release)
